// StudentView およびその子コンポーネントで使用する共通スタイル
export const styles = {
  container: { height: '100vh', width: '100vw', display: 'flex', flexDirection: 'column', backgroundColor: '#f4f7f9', position: 'fixed', top: 0, left: 0, overflow: 'hidden' },
  header: { height: '60px', backgroundColor: '#2c3e50', color: '#fff', display: 'flex', alignItems: 'center', padding: '0 20px', zIndex: 1000, boxShadow: '0 2px 5px rgba(0,0,0,0.2)' },
  hamburgerBtn: { background: 'none', border: 'none', color: '#fff', fontSize: '1.5rem', cursor: 'pointer', marginRight: '20px' },
  headerTitle: { fontSize: '1.2rem', fontWeight: 'bold', flex: 1 },
  headerUserInfo: { fontSize: '0.9rem', color: '#bdc3c7' },
  body: { flex: 1, display: 'flex', overflow: 'hidden' },
  sidebar: (isOpen) => ({ width: isOpen ? '260px' : '0px', backgroundColor: '#34495e', color: '#ecf0f1', display: 'flex', flexDirection: 'column', overflow: 'hidden', transition: 'width 0.3s ease', flexShrink: 0 }),
  profileArea: { padding: '20px', borderBottom: '1px solid rgba(255,255,255,0.1)', minWidth: '260px' },
  studentName: { fontSize: '1.2rem', fontWeight: 'bold', marginBottom: '5px' },
  schoolInfo: { display: 'flex', alignItems: 'center' },
  infoBadge: { background: 'rgba(255,255,255,0.15)', padding: '3px 8px', borderRadius: '4px', fontSize: '0.75rem' },
  nav: { flex: 1, display: 'flex', flexDirection: 'column', gap: '5px', padding: '10px', minWidth: '260px' },
  navItem: (isActive) => ({ background: isActive ? '#3498db' : 'none', color: '#fff', border: 'none', padding: '12px 15px', borderRadius: '6px', fontSize: '1rem', textAlign: 'left', cursor: 'pointer', width: '100%', marginBottom: '5px' }),
  logoutBtn: { background: 'rgba(231, 76, 60, 0.2)', border: 'none', color: '#e74c3c', padding: '10px', cursor: 'pointer', margin: '10px', borderRadius: '6px' },
  main: { flex: 1, padding: '30px', overflowY: 'auto', position: 'relative' },
  contentArea: { maxWidth: '1000px', margin: '0 auto' },
  mainTitle: { fontSize: '2rem', fontWeight: 'bold', marginBottom: '20px', color: '#2c3e50', textAlign: 'center' },
  mainSubTitle: { fontSize: '1.1rem', color: '#7f8c8d', marginBottom: '20px', textAlign: 'center' },
  cardContainer: { display: 'flex', justifyContent: 'center', marginTop: '20px' },
  buttonGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px', width: '100%', maxWidth: '700px' },
  btnMaru: (isS, isA) => ({ height: '180px', borderRadius: '20px', border: 'none', background: isS ? '#ccc' : (isA ? '#ffcc99' : 'linear-gradient(135deg, #e67e22, #f39c12)'), color: '#fff', fontSize: '1.4rem', fontWeight: 'bold', cursor: isA ? 'not-allowed' : 'pointer' }),
  btnQuestion: (isS, isA) => ({ height: '180px', borderRadius: '20px', border: 'none', background: isS ? '#ccc' : (isA ? '#b3e0ff' : 'linear-gradient(135deg, #3498db, #5dade2)'), color: '#fff', fontSize: '1.4rem', fontWeight: 'bold', cursor: isA ? 'not-allowed' : 'pointer' }),
  completeWrapper: { textAlign: 'center' },
  requestStatusText: { fontSize: '1.5rem', color: '#2c3e50', marginBottom: '15px' },
  completeMsgCard: { backgroundColor: '#fff', padding: '20px', borderRadius: '15px', border: '4px solid #3498db' },
  queueNumberSmall: { fontSize: '2rem', color: '#3498db', fontWeight: 'bold' },
  waitingCard: { backgroundColor: '#fff', padding: '40px', borderRadius: '20px', textAlign: 'center', border: '5px solid #27ae60' },
  waitingTitle: { color: '#27ae60', fontSize: '1.4rem', marginBottom: '10px' },
  queueNumber: { fontSize: '5rem', fontWeight: 'bold' },
  waitingText: { marginTop: '20px', color: '#666' },
  progressTableWrapper: { backgroundColor: '#fff', padding: '20px', borderRadius: '15px', boxShadow: '0 4px 15px rgba(0,0,0,0.05)' },
  progressTable: { width: '100%', borderCollapse: 'collapse' },
  tableHeader: { backgroundColor: '#f8f9fa', borderBottom: '2px solid #dee2e6' },
  th: { padding: '12px', textAlign: 'left', color: '#495057' },
  tr: { borderBottom: '1px solid #eee' },
  tdSubject: { padding: '15px', fontWeight: 'bold', borderRight: '1px solid #eee' },
  tdText: { padding: '15px' },
  td: { padding: '10px' },
  tdUnitDisplay: { padding: '15px', color: '#3498db', fontSize: '0.85rem' },
  selectBtn: { padding: '6px 12px', background: '#3498db', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' },
  submitProgressBtn: { width: '100%', padding: '15px', background: '#27ae60', color: '#fff', border: 'none', borderRadius: '10px', fontSize: '1.1rem', fontWeight: 'bold', cursor: 'pointer', marginTop: '20px' },
  filterBar: { marginBottom: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  gradeTab: (active) => ({ padding: '8px 18px', margin: '0 5px', borderRadius: '20px', border: 'none', backgroundColor: active ? '#3498db' : '#dfe6e9', color: active ? '#fff' : '#636e72', cursor: 'pointer', fontWeight: 'bold' }),
  overlay: { position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', background: 'rgba(0,0,0,0.5)', zIndex: 2000, display: 'flex', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#fff', padding: '20px', borderRadius: '20px', width: '95%', maxWidth: '900px', maxHeight: '90vh', display: 'flex', flexDirection: 'column' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #3498db', paddingBottom: '10px', marginBottom: '15px' },
  modalTitle: { margin: 0, color: '#2c3e50' },
  modalCloseX: { background: 'none', border: 'none', fontSize: '24px', cursor: 'pointer', color: '#ccc' },
  unitListScroll: { flex: 1, overflowY: 'auto' },
  unitTable: { width: '100%', borderCollapse: 'collapse',border: '1px solid #ddd', },
  modalTh: { border: '1px solid #333', padding: '8px', backgroundColor: '#f8f9fa' },
  modalTdMerge: { border: '1px solid #333', padding: '10px', textAlign: 'center', fontWeight: 'bold' },
  modalTdUnit: { border: '1px solid #333', padding: '10px' },
  modalTdPage: { border: '1px solid #333', padding: '10px', textAlign: 'center', color: '#7f8c8d' },
  modalTdCheck: { border: '1px solid #333', padding: '10px', textAlign: 'center' },
  modalFooter: { marginTop: '15px', textAlign: 'center' },
  confirmBtn: { padding: '12px 40px', background: '#3498db', color: '#fff', border: 'none', borderRadius: '25px', fontWeight: 'bold', cursor: 'pointer' },
  reviewCard: { backgroundColor: '#fff', padding: '15px', borderRadius: '12px', marginBottom: '15px', borderLeft: '6px solid #27ae60', boxShadow: '0 4px 10px rgba(0,0,0,0.05)' },
  reviewDate: { fontSize: '0.85rem', color: '#888', marginBottom: '10px' },
  reviewSection: { marginBottom: '10px' },
  reviewText: { fontSize: '0.95rem', marginTop: '4px', whiteSpace: 'pre-wrap', color: '#333' }
};